### ISSUE TITLE
"host it yourself" - point people to LetsEncrypt for legit certs

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-doc#84]
Chrome on MacOS is a particular pain for the ZAC. Until ACME can be implemented by ZAC it'd be good to point people as to how to create legit certs using lets encrypt

**Comment by qrkourier** [comment]
Seems unlikely a MacOS device is directly exposed to the internet, so I'm guessing this pertains more to the local no docker quickstart than host it yourself. The main difference is external DNS SANs in the host it yourself quickstart, right?

Sounds like a job for that project that Michael Q is working on, i.e. access ZAC with HTTPS through a reverse proxy with a valid cert instead of directly.

**Comment by dovholuknf** [comment]
You're not understanding the issue. This is for ZAC to use "alternate certs".

**Comment by poppaLol** [comment]
I went through doing this recently. 

I found that I could use one of the alternative certs fields in the controller config yaml. (This is from a quickstart in my case)

```
web:
  - name: client-management
    identity:
      ..
      alt_server_certs:
      - server_cert: "/etc/letsencrypt/live/XXX/fullchain.pem"
        server_key:  "/etc/letsencrypt/live/XXX/privkey.pem"
```
I am not sure if this is the intended way to use these fields, but if it is, then the process is pretty simple.

1) Install LetsEncrypt CertBot
2) Get and access token for your DNS provider (for me this was digital ocean) and configure it in the ini file
3) Alter the keys and restart the service
4) For bonus points - restart the controller service after the automatic renewal done with the cron

I can pop a branch together for this if this makes sense?

I thought maybe inserting a section under the zac\index.mdx after the '## Login and use ZAC' section to explain might be best.
